import matplotlib
matplotlib.use('Qt5Agg')
from matplotlib import pyplot as plt
from matplotlib.colors import ListedColormap
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import numpy as np


# value z
fig = plt.figure(1, figsize=[16, 9], dpi=250)
x = np.arange(-50, 51, 1)
y = 1000 - 20 * np.abs(x)
plt.plot(x,y)
plt.xlabel("z", fontsize=60)
plt.ylabel("value", fontsize=60)
plt.ylim([0, 1010])
plt.xlim(-50, 50)
plt.xticks(np.arange(-50,51,10))
plt.tick_params(axis="both", which="major", labelsize=40)
plt.tight_layout()
plt.savefig(r"D:\ECRC_AG_CMR\3 - Promotion\Project ReslicingTool\6 - Analysis\Figures\Appendix\Validation Value\value_z.jpg")
plt.cla()

# value x /y
fig = plt.figure(2, figsize=[16, 9], dpi=250)
x = np.arange(-50, 51, 1)
y = np.ones(np.shape(x))
plt.plot(x,y)
plt.xlabel("x", fontsize=60)
plt.ylabel("value", fontsize=60)
plt.ylim([0, 1.33])
plt.xlim(-50, 50)
plt.xticks(np.arange(-50,51,10))
plt.yticks([0,1], labels=["0", "$v_{z}$"])
plt.tick_params(axis="both", which="major", labelsize=40)
plt.tight_layout()
plt.savefig(r"D:\ECRC_AG_CMR\3 - Promotion\Project ReslicingTool\6 - Analysis\Figures\Appendix\Validation Value\value_x.jpg")
plt.xlabel("y", fontsize=60)
plt.tight_layout()
plt.savefig(r"D:\ECRC_AG_CMR\3 - Promotion\Project ReslicingTool\6 - Analysis\Figures\Appendix\Validation Value\value_y.jpg")
plt.cla()

# slice thickness visualize inplane
fig = plt.figure(3, figsize=[16, 9], dpi=250)
x = np.arange(-50, 51, 1)
y = 1000 - 20 * np.abs(x)
plt.plot(x,y)
plt.scatter([0], [1000], c="red", zorder=10)
plt.vlines([-5, 5], 0, 1010, colors="red", linestyles="--")
plt.xlabel("direction z", fontsize=60)
plt.ylabel("value", fontsize=60)
plt.ylim([0, 1010])
plt.xlim(-50, 50)
plt.xticks(np.arange(-50,51,10))
plt.tick_params(axis="both", which="major", labelsize=40)
plt.tight_layout()
plt.savefig(r"D:\ECRC_AG_CMR\3 - Promotion\Project ReslicingTool\6 - Analysis\Figures\Appendix\Validation Value\value_slice_thickness_inplane.jpg")
plt.cla()

# slice thickness visualize perplane
fig = plt.figure(2, figsize=[16, 9], dpi=250)
x = np.arange(-50, 51, 1)
y = np.ones(np.shape(x))
plt.plot(x,y)
plt.scatter([0], [1], c="red", zorder=10)
plt.vlines([-5, 5], 0, 1.33, colors="red", linestyles="--")
plt.ylabel("value", fontsize=60)
plt.ylim([0, 1.33])
plt.xlim(-50, 50)
plt.xticks(np.arange(-50,51,10))
plt.yticks([0,1], labels=["0", "$v_{z}$"])
plt.xlabel("direction y", fontsize=60)
plt.tick_params(axis="both", which="major", labelsize=40)
plt.tight_layout()
plt.savefig(r"D:\ECRC_AG_CMR\3 - Promotion\Project ReslicingTool\6 - Analysis\Figures\Appendix\Validation Value\value_slice_thickness_perplane.jpg")
plt.cla()

# slice thickness visualize diagplane
fig = plt.figure(3, figsize=[16, 9], dpi=250)
x = np.arange(-50, 51, 1)
y = 1000 - 20 * np.abs(x)
plt.plot(x,y)
plt.scatter([0], [1000], c="red", zorder=10)
plt.vlines([-5, 5], 0, 1010, colors="red", linestyles="--")
plt.scatter([3], [940], c="orange", zorder=10)
plt.vlines([-2, 8], 0, 1010, colors="orange", linestyles="--")
plt.scatter([-25], [500], c="purple", zorder=10)
plt.vlines([-30, -20], 0, 1010, colors="purple", linestyles="--")
plt.xlabel("direction y-z", fontsize=60)
plt.ylabel("value", fontsize=60)
plt.ylim([0, 1010])
plt.xlim(-50, 50)
plt.xticks(np.arange(-50,51,10))
plt.tick_params(axis="both", which="major", labelsize=40)
plt.tight_layout()
plt.savefig(r"D:\ECRC_AG_CMR\3 - Promotion\Project ReslicingTool\6 - Analysis\Figures\Appendix\Validation Value\value_slice_thickness_diagplane.jpg")
plt.cla()
